baseURL = "https://honeybeepodcast.com"
disqusShortname = ""
googleAnalytics = ""
languageCode = "en-us"
languageName = "En"
paginate = "3"
summaryLength = "15"
theme = "bigspring"
title = "Honeybee Podcast"
[markup.goldmark.renderer]
unsafe = true
[[menu.footer_left]]
URL = "#"
name = "About Honeybee"
url = "#"
weight = 1
[[menu.footer_middle]]
URL = "#"
name = "Podcast"
url = "https://anchor.fm/honeybee-podcast"
weight = 1
[[menu.footer_right]]
name = "Contact"
url = "/contact"
weight = 3
[[menu.footer_right]]
URL = "terms-conditions"
name = "Terms & Conditions"
weight = 1
[[menu.footer_right]]
URL = "privacy-policy"
name = "Privacy Policy"
weight = 2
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 3
[[menu.main]]
URL = "pricing"
name = "Pricing"
weight = 2
[[menu.main]]
URL = "blog"
name = "Blog"
weight = 1
[params]
author = "Honeybee Podcast"
contact_form_action = "mailto:thehoneybeepodcast@gmail.com"
copyright = "Design By [Honeybee Podcast](https://honeybeepodcast.com) | Develop By [Honeybee Podcast](https://honeybeepodcast.com)"
description = "The Honeybee Podcast: Debugging Persona Finance"
footer_content = "The Honeybee Podcast debugs personal finance through interviews with real living hoomans in Snigapore."
footer_menu_left = "Company"
footer_menu_middle = "Product"
footer_menu_right = "Support"
logo = "images/honeybee-podcast.png"
logo_width = "100px"
[params.navigation_button]
enable = true
label = "Get Started"
link = "contact"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[params.preloader]
enable = false
preloader = ""
[[params.social]]
icon = "ti-instagram"
link = "https://wwww.instagram.com/honeybeepodcast"
title = "instagram"
[[params.social]]
icon = "ti-twitter-alt"
link = "https://twitter.com/honeybeepodcast"
title = "twitter"
